// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0OV-74X8yyOWysqWe4x9-XcspFZOkag',
    appId: '1:784992969089:web:e8eb22a58127f2d0fc0880',
    messagingSenderId: '784992969089',
    projectId: 'instagramclone-f0cd1',
    authDomain: 'instagramclone-f0cd1.firebaseapp.com',
    storageBucket: 'instagramclone-f0cd1.firebasestorage.app',
    measurementId: 'G-43BSBC257P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGhmevEWcA1nMhfyHjRP8PirR3Gg9popM',
    appId: '1:784992969089:android:0cc5ed150ce31fa1fc0880',
    messagingSenderId: '784992969089',
    projectId: 'instagramclone-f0cd1',
    storageBucket: 'instagramclone-f0cd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB93oqzg4zvwHDm1D3l1UkMCr_YN2i8APU',
    appId: '1:784992969089:ios:eba89403104f05d0fc0880',
    messagingSenderId: '784992969089',
    projectId: 'instagramclone-f0cd1',
    storageBucket: 'instagramclone-f0cd1.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB93oqzg4zvwHDm1D3l1UkMCr_YN2i8APU',
    appId: '1:784992969089:ios:eba89403104f05d0fc0880',
    messagingSenderId: '784992969089',
    projectId: 'instagramclone-f0cd1',
    storageBucket: 'instagramclone-f0cd1.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0OV-74X8yyOWysqWe4x9-XcspFZOkag',
    appId: '1:784992969089:web:7e6980cf0c7582e8fc0880',
    messagingSenderId: '784992969089',
    projectId: 'instagramclone-f0cd1',
    authDomain: 'instagramclone-f0cd1.firebaseapp.com',
    storageBucket: 'instagramclone-f0cd1.firebasestorage.app',
    measurementId: 'G-HE0RBHVGG0',
  );
}
